package org.example.academic.system.service;

import org.example.academic.system.dto.AssessmentWeightReportDTO;
import org.example.academic.system.model.AcademicClass;
import org.example.academic.system.model.Assessment;
import org.example.academic.system.model.User;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.List;

public class AssessmentWeightReportService {

    private static final Logger logger = LoggerFactory.getLogger(AssessmentWeightReportService.class);

    // Adicionado parâmetro User user para cumprir a regra de auditoria de Role (AC7)
    public List<AssessmentWeightReportDTO> generate(List<AcademicClass> classes, User user) {
        if (user != null) {
            logger.info("Audit: Assessment weight report generated by user with role: {}", user.getRole());
        }

        List<AssessmentWeightReportDTO> report = new ArrayList<>();

        if (classes == null || classes.isEmpty()) {
            return report;
        }

        for (AcademicClass c : classes) {
            double totalWeight = 0.0;

            if (c.getAssessments() != null) {
                for (Assessment a : c.getAssessments()) {
                    totalWeight += a.getWeight();
                }
            }

            String status = (Math.abs(totalWeight - 1.0) < 0.0001) ? "VALID" : "INVALID";

            report.add(new AssessmentWeightReportDTO(
                    c.getCode(),
                    c.getTitle(),
                    totalWeight,
                    status
            ));
        }

        return report;
    }
}