package org.example.academic.system.service;

import org.example.academic.system.dto.ClassAssessmentReportDTO;
import org.example.academic.system.model.AcademicClass;
import org.example.academic.system.model.Assessment;
import org.example.academic.system.model.User;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.List;

public class ClassAssessmentReportService {

    private static final Logger logger = LoggerFactory.getLogger(ClassAssessmentReportService.class);

    // Adicionado parâmetro User user para cumprir a regra de auditoria de Role (AC6)
    public List<ClassAssessmentReportDTO> generate(List<AcademicClass> classes, User user) {
        if (user != null) {
            logger.info("Audit: Class assessment summary report generated by user with role: {}", user.getRole());
        }

        List<ClassAssessmentReportDTO> report = new ArrayList<>();

        if (classes == null || classes.isEmpty()) {
            return report;
        }

        for (AcademicClass c : classes) {
            if (c.getAssessments() == null || c.getAssessments().isEmpty()) {
                report.add(new ClassAssessmentReportDTO(
                        c.getCode(),
                        c.getTitle(),
                        null,
                        null,
                        null
                ));
            } else {
                for (Assessment a : c.getAssessments()) {
                    report.add(new ClassAssessmentReportDTO(
                            c.getCode(),
                            c.getTitle(),
                            a.getType(),
                            a.getValue(),
                            a.getWeight()
                    ));
                }
            }
        }

        return report;
    }
}