package org.example.academic.system.service;

import org.example.academic.system.dto.PersistenceConfigReportDTO;
import org.example.academic.system.model.PersistenceType;
import org.example.academic.system.model.User;
import org.example.academic.system.exception.AuthorizationException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.List;
import java.util.Collections;

public class PersistenceConfigReportService {

    private static final Logger logger = LoggerFactory.getLogger(PersistenceConfigReportService.class);

    // Validando autorização estrita (AC4) e injetando log de auditoria (AC6)
    public List<PersistenceConfigReportDTO> generate(PersistenceType type, User user) {
        if (user == null || user.getRole() != User.Role.ADMIN) {
            throw new AuthorizationException("Operation denied: Only administrators can view persistence configurations.");
        }

        logger.info("Audit: Persistence configuration report generated by user with role: {}", user.getRole());

        if (type == null) {
            return Collections.emptyList();
        }

        return List.of(
                new PersistenceConfigReportDTO(type.name())
        );
    }
}