package org.example.academic.system.logging;

import org.example.academic.system.model.Role;

import java.util.logging.Logger;

/**
 * TUS-2394 - log da geração de relatórios, incluindo o perfil do usuário.
 */
public final class ReportAuditLogger {

    private static final Logger log = AppLogger.get(ReportAuditLogger.class);

    private ReportAuditLogger() {
    }

    public static void generated(String reportName, Role role) {
        String r = (role == null) ? "UNKNOWN" : role.name();
        log.info("Report '" + reportName + "' generated by role " + r);
    }
}
